default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: 
  host: localhost
  database: become_manga_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost 
  database: become_manga_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

# production:
#   adapter:  mysql2
#   encoding: utf8
#   pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout:  5000
#   username: <%= ENV["MC_DB_USERNAME"] %>
#   password: <%= ENV["MC_DB_PASSWORD"] %>
#   database: <%= ENV["MC_DATABASE"] %>
#   host:     <%= ENV["MC_DB_HOSTNAME"] %>